/**
 * Core Type Definitions for Crowd Risk Engine
 * 
 * This file contains all TypeScript interfaces and types for the crowd risk monitoring system.
 * Requirements: 1.1, 1.3, 6.1, 6.4
 */

// ============================================================================
// Enums
// ============================================================================

/**
 * Threshold levels for crowd density monitoring
 * Requirement 1.3: Support multiple threshold levels
 */
export enum ThresholdLevel {
  NORMAL = 'normal',
  WARNING = 'warning',
  CRITICAL = 'critical',
  EMERGENCY = 'emergency',
}

/**
 * Notification channels for alert delivery
 * Requirement 2.5: Multi-channel notification support
 */
export enum NotificationChannel {
  PUSH = 'push',
  SMS = 'sms',
  EMAIL = 'email',
}

/**
 * Alert event types
 * Requirement 1.2, 1.4: Different types of alert events
 */
export enum AlertType {
  THRESHOLD_VIOLATION = 'threshold_violation',
  DENSITY_NORMALIZED = 'density_normalized',
  EMERGENCY_ACTIVATED = 'emergency_activated',
  EMERGENCY_DEACTIVATED = 'emergency_deactivated',
}

/**
 * Area types for monitored locations
 */
export enum AreaType {
  ENTRANCE = 'entrance',
  CORRIDOR = 'corridor',
  GATHERING_SPACE = 'gathering_space',
  EXIT = 'exit',
}

/**
 * Emergency mode trigger types
 * Requirement 5.1, 5.4: Automatic and manual emergency activation
 */
export enum EmergencyTrigger {
  AUTOMATIC = 'automatic',
  MANUAL = 'manual',
}

/**
 * Density measurement units
 * Requirement 1.1: Support different density measurement units
 */
export enum DensityUnit {
  PEOPLE_PER_SQM = 'people_per_sqm',
  PERCENTAGE = 'percentage',
}

/**
 * Admin roles for role-based access control
 * Task 15.1: Define admin roles for authorization
 */
export enum AdminRole {
  SUPER_ADMIN = 'super_admin',
  SAFETY_ADMIN = 'safety_admin',
  MONITOR_ONLY = 'monitor_only',
}

/**
 * Permissions for role-based access control
 * Task 15.1: Define permissions for authorization
 */
export enum Permission {
  CONFIGURE_THRESHOLDS = 'configure_thresholds',
  ACTIVATE_EMERGENCY = 'activate_emergency',
  VIEW_ONLY = 'view_only',
  MANAGE_USERS = 'manage_users',
  ACKNOWLEDGE_ALERTS = 'acknowledge_alerts',
  VIEW_ANALYTICS = 'view_analytics',
}

/**
 * Role-to-permissions mapping
 * Task 15.1: Define which permissions each role has
 */
export const RolePermissions: Record<AdminRole, Permission[]> = {
  [AdminRole.SUPER_ADMIN]: [
    Permission.CONFIGURE_THRESHOLDS,
    Permission.ACTIVATE_EMERGENCY,
    Permission.MANAGE_USERS,
    Permission.ACKNOWLEDGE_ALERTS,
    Permission.VIEW_ANALYTICS,
    Permission.VIEW_ONLY,
  ],
  [AdminRole.SAFETY_ADMIN]: [
    Permission.CONFIGURE_THRESHOLDS,
    Permission.ACTIVATE_EMERGENCY,
    Permission.ACKNOWLEDGE_ALERTS,
    Permission.VIEW_ANALYTICS,
    Permission.VIEW_ONLY,
  ],
  [AdminRole.MONITOR_ONLY]: [
    Permission.VIEW_ONLY,
    Permission.VIEW_ANALYTICS,
  ],
};

// ============================================================================
// Core Data Models
// ============================================================================

/**
 * Density reading from monitoring system
 * Requirement 1.1: Real-time density measurement with millisecond precision
 * Requirement 1.5: Timestamp with millisecond precision
 */
export interface DensityReading {
  areaId: string;
  timestamp: number; // Unix timestamp in milliseconds
  densityValue: number;
  unit: DensityUnit;
  metadata?: Record<string, unknown>;
}

/**
 * Threshold configuration for an area
 * Requirement 6.1: Custom threshold values per area
 * Requirement 6.2: Time-based threshold profiles
 * Requirement 6.4: Threshold validation (warning < critical < emergency)
 */
export interface ThresholdConfig {
  areaId: string;
  warningThreshold: number;
  criticalThreshold: number;
  emergencyThreshold: number;
  timeProfile?: TimeBasedProfile[];
}

/**
 * Time-based threshold profile
 * Requirement 6.2: Different thresholds for different times
 */
export interface TimeBasedProfile {
  startTime: string; // HH:mm format
  endTime: string; // HH:mm format
  thresholds: {
    warningThreshold: number;
    criticalThreshold: number;
    emergencyThreshold: number;
  };
}

/**
 * Threshold evaluation result
 * Requirement 1.2: Threshold evaluation and level determination
 * Requirement 1.3: Multiple threshold levels
 */
export interface ThresholdEvaluation {
  areaId: string;
  currentLevel: ThresholdLevel;
  previousLevel: ThresholdLevel;
  densityValue: number;
  threshold: number;
  timestamp: number;
  isEscalation: boolean;
}

/**
 * Alert event generated by the system
 * Requirement 1.2: Alert event generation
 * Requirement 1.4: Alert metadata and context
 */
export interface AlertEvent {
  id: string;
  type: AlertType;
  severity: ThresholdLevel;
  areaId: string;
  areaName: string;
  densityValue: number;
  threshold: number;
  timestamp: number;
  metadata: AlertMetadata;
}

/**
 * Alert metadata with contextual information
 * Requirement 2.2: Location, density, threshold, and timestamp in notifications
 * Requirement 3.2: Suggested actions and alternative routes
 */
export interface AlertMetadata {
  location: string;
  affectedPilgrimCount?: number;
  suggestedActions?: string[];
  alternativeRoutes?: string[];
}

/**
 * Monitored area definition
 * Requirement 1.1: Area-based monitoring
 */
export interface MonitoredArea {
  id: string;
  name: string;
  location: {
    latitude: number;
    longitude: number;
  };
  capacity: number;
  adjacentAreas: string[];
  metadata: {
    type: AreaType;
    description: string;
  };
}

// ============================================================================
// Notification Models
// ============================================================================

/**
 * Admin notification configuration
 * Requirement 2.5: Configurable notification channels and preferences
 */
export interface AdminNotificationConfig {
  adminId: string;
  channels: NotificationChannel[];
  severityFilter: ThresholdLevel[];
  areaFilter?: string[];
}

/**
 * Notification delivery result
 * Requirement 2.4: Delivery success tracking
 */
export interface NotificationResult {
  adminId: string;
  channel: NotificationChannel;
  delivered: boolean;
  deliveryTime: number; // milliseconds
  error?: string;
}

/**
 * Notification delivery statistics
 * Requirement 2.4: 99.5% delivery success rate monitoring
 */
export interface NotificationStats {
  totalSent: number;
  successRate: number;
  averageDeliveryTime: number;
  failuresByChannel: Record<string, number>;
}

/**
 * Pilgrim notification message
 * Requirement 3.1: Pilgrim notifications with guidance
 * Requirement 3.2: Clear guidance and suggested actions
 */
export interface PilgrimNotification {
  alertId: string;
  areaId: string;
  severity: ThresholdLevel;
  message: string;
  suggestedActions: string[];
  alternativeRoutes?: string[];
  timestamp: number;
}

// ============================================================================
// Visual Indicator Models
// ============================================================================

/**
 * Visual indicator state for monitoring interface
 * Requirement 4.1: Red blinking indicators for critical conditions
 * Requirement 4.2: Color-coded severity levels
 * Requirement 4.3: 2 Hz blink rate for emergency
 */
export interface IndicatorState {
  areaId: string;
  color: 'green' | 'yellow' | 'red';
  blinking: boolean;
  blinkRate?: number; // cycles per second (Hz)
  lastUpdate: number;
}

// ============================================================================
// Emergency Mode Models
// ============================================================================

/**
 * Emergency mode state
 * Requirement 5.1: Automatic emergency activation
 * Requirement 5.2: Expanded notification reach
 * Requirement 5.4: Manual activation by authorized admins
 */
export interface EmergencyMode {
  active: boolean;
  activatedAt?: number;
  activatedBy: EmergencyTrigger;
  adminId?: string;
  triggerAreaId: string;
  affectedAreas: string[];
}

// ============================================================================
// Configuration and Audit Models
// ============================================================================

/**
 * Configuration audit log entry
 * Requirement 6.5: Audit log of threshold configuration changes
 */
export interface ConfigAuditEntry {
  timestamp: number;
  adminId: string;
  areaId: string;
  previousConfig: ThresholdConfig;
  newConfig: ThresholdConfig;
  reason?: string;
}

/**
 * Alert log entry for history tracking
 * Requirement 1.4: Alert history and tracking
 * Requirement 2.1: Alert acknowledgment
 */
export interface AlertLogEntry {
  id: string;
  alertEvent: AlertEvent;
  notificationResults: {
    adminNotifications: NotificationResult[];
    pilgrimCount: number;
  };
  acknowledgments: AlertAcknowledgment[];
  resolution?: AlertResolution;
}

/**
 * Alert acknowledgment record
 * Requirement 2.1: Alert acknowledgment workflow
 */
export interface AlertAcknowledgment {
  adminId: string;
  timestamp: number;
}

/**
 * Alert resolution record
 * Requirement 1.4: Alert resolution tracking
 */
export interface AlertResolution {
  resolvedAt: number;
  resolvedBy: string;
  notes: string;
}

/**
 * Density history entry for time-series data
 * Requirement 1.1: Historical density tracking
 */
export interface DensityHistoryEntry {
  areaId: string;
  timestamp: number;
  densityValue: number;
  thresholdLevel: ThresholdLevel;
}

// ============================================================================
// Validation Models
// ============================================================================

/**
 * Validation result for threshold configurations
 * Requirement 6.4: Threshold validation
 */
export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
}

/**
 * Validation error details
 */
export interface ValidationError {
  field: string;
  message: string;
  code: string;
}

// ============================================================================
// Service Interface Types
// ============================================================================

/**
 * Density monitor service interface
 * Requirement 1.1: Real-time density monitoring
 */
export interface DensityMonitor {
  startMonitoring(areaIds: string[]): void;
  stopMonitoring(areaId: string): void;
  getCurrentDensity(areaId: string): Promise<DensityReading | null>;
  onDensityUpdate(callback: (reading: DensityReading) => void): () => void;
}

/**
 * Threshold evaluator service interface
 * Requirement 1.2: Threshold evaluation
 * Requirement 6.3: Configuration update propagation
 */
export interface ThresholdEvaluator {
  evaluate(reading: DensityReading): ThresholdEvaluation;
  updateThresholds(config: ThresholdConfig): void;
  getActiveThresholds(areaId: string): Promise<Omit<ThresholdConfig, 'timeProfile'> | null>;
  validateThresholds(config: ThresholdConfig): ValidationResult;
}

/**
 * Alert engine service interface
 * Requirement 1.2: Alert event generation and routing
 * Requirement 1.4: Alert history
 */
export interface AlertEngine {
  processEvaluation(evaluation: ThresholdEvaluation): void;
  subscribeToAlerts(callback: (alert: AlertEvent) => void): () => void;
  getAlertHistory(areaId: string, limit: number): Promise<AlertEvent[]>;
  acknowledgeAlert(alertId: string, adminId: string): Promise<void>;
}

/**
 * Admin notifier service interface
 * Requirement 2.1: Admin notification delivery
 * Requirement 2.4: Delivery statistics
 */
export interface AdminNotifier {
  sendAlert(alert: AlertEvent, admins: string[]): Promise<NotificationResult[]>;
  configureNotifications(config: AdminNotificationConfig): void;
  getDeliveryStats(): Promise<NotificationStats>;
}

/**
 * Pilgrim notifier service interface
 * Requirement 3.1: Pilgrim notification delivery
 * Requirement 3.4: Rate limiting
 * Requirement 3.5: All-clear notifications
 */
export interface PilgrimNotifier {
  notifyArea(alert: AlertEvent, areaId: string): Promise<number>;
  sendAllClear(areaId: string): Promise<number>;
  checkRateLimit(pilgrimId: string, areaId: string): boolean;
}

/**
 * Visual indicator controller service interface
 * Requirement 4.1: Visual indicator management
 * Requirement 4.4: Real-time indicator updates
 */
export interface VisualIndicatorController {
  updateIndicator(areaId: string, level: ThresholdLevel): void;
  getIndicatorState(areaId: string): IndicatorState;
  subscribeToUpdates(callback: (state: IndicatorState) => void): () => void;
}

/**
 * Emergency mode manager service interface
 * Requirement 5.1: Emergency mode activation
 * Requirement 5.4: Manual activation
 * Requirement 5.5: Deactivation logging
 */
export interface EmergencyModeManager {
  activateEmergency(areaId: string, trigger: EmergencyTrigger, adminId?: string): void;
  deactivateEmergency(adminId: string): void;
  isEmergencyActive(): boolean;
  getEmergencyState(): EmergencyMode | null;
  onEmergencyStateChange(callback: (state: EmergencyMode | null) => void): () => void;
}

/**
 * Threshold configuration manager service interface
 * Requirement 6.1: Threshold configuration management
 * Requirement 6.5: Configuration audit logging
 */
export interface ThresholdConfigManager {
  saveConfig(config: ThresholdConfig): Promise<void>;
  getConfig(areaId: string): Promise<ThresholdConfig | null>;
  getAllConfigs(): Promise<ThresholdConfig[]>;
  getAuditLog(areaId: string): Promise<ConfigAuditEntry[]>;
}

// ============================================================================
// State Management Types
// ============================================================================

/**
 * Global alert context state
 * Used for React Context API state management
 */
export interface AlertContextState {
  activeAlerts: AlertEvent[];
  emergencyMode: EmergencyMode | null;
  indicatorStates: Map<string, IndicatorState>;
  unacknowledgedCount: number;
}

/**
 * Admin dashboard state
 * Used for admin interface state management
 */
export interface AdminDashboardState {
  areas: MonitoredArea[];
  currentDensities: Map<string, DensityReading>;
  recentAlerts: AlertEvent[];
  notificationConfig: AdminNotificationConfig;
}

// ============================================================================
// Error Handling Types
// ============================================================================

/**
 * Retry configuration for error handling
 */
export interface RetryConfig {
  maxAttempts: number;
  backoffMs: number;
  backoffMultiplier: number;
}

/**
 * Error handler service interface
 */
export interface ErrorHandler {
  handleDataStreamError(error: Error, areaId: string): void;
  handleNotificationFailure(result: NotificationResult): void;
  handleConfigurationError(error: ValidationError): void;
  handleSystemError(error: Error): void;
}
